version: "2"

services:
  zeebe:
    restart: always
    container_name: zeebe_broker
    image: camunda/zeebe:0.22.1
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      - ZEEBE_GATEWAY_REQUEST_TIMEOUT=5s
